### ISSUE TITLE
Meta issue: Claim a source Python function to port

### ISSUE THREAD

**Issue by scooter-dangle** [rust-dc/fish-manpage-completions#2]
For our initial naïve port, we want to do a largely Python-function-to-Rust-fn translation.

To coördinate, grab a function and post a comment here of the file (main vs deroff) and the function name.

For example, if the `splorp(...)` function in `src/main.rs` looks particularly juicy, post something like the following below

> src/main.rs:splorp is mine! And I'll never let it go!

and then _fine_...it's _yours_...you can _have_ it...jeez

Note: If you run into issues you want to discuss while porting a function, open a new, dedicated issue or speak out on [zulip](https://rust-dc.zulipchat.com/). We don't want to add much more to this thread than work claiming/allocation.

- - -

Important note: before implementing something you've claimed, ensure it's actually _used_ somewhere. If it's totally unused, you can just delete it from the commented-out Python source.

- - -
### `main.rs`
- [x] `fn main` :imp:—#106

- - -

`<Verbosity as Default>::`
- [x] `fn default`

- - -

`App::`
- [x] `fn add_diagnostic`
- [x] `fn flush_diagnostics`

- - -

- [x] `fn unquote_double_quotes`
- [x] `fn unquote_single_quotes`
- [x] `fn fish_escape_single_quote`—[claimed by PureW](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473124869)
- [x] `fn lossy_unicode`—#31
- [x] `fn output_complete_command`
- [x] `fn complete_command`
- [x] `fn built_command`—[claimed by scooter-dangle](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-481959790)
- [x] `fn remove_groff_formatting`—[claimed by PureW](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473124869)

- - -

`<Type1 as ManParser>::`
- [x] `fn is_my_type`—[claimed by scooter-dangle](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473981803)—#24
- [x] `fn parse_man_page`—claimed by @pickfire —#81

- - -

`Type1::`
- [x] `fn fallback`—claimed by @pickfire—#72
- [x] `fn fallback2`—claimed by @pickfire—#72

- - -

`<Type2 as ManParser>::`
- [x] `fn is_my_type`—[claimed by scooter-dangle](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473981803)—#24
- [x] `fn parse_man_page`—claimed by @pickfire —#81

- - -

`<Type3 as ManParser>::`
- [x] `fn is_my_type`—[claimed by scooter-dangle](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473981803)—#24
- [x] `fn parse_man_page` ~~—claimed by @dlrobertson~~—stolen by @pickfire —#81

- - -

`<Type4 as ManParser>::`
- [x] `fn is_my_type`—[claimed by scooter-dangle](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473981803)—#24
- [x] `fn parse_man_page`—claimed by @pickfire —#81

- - -

`<TypeDarwin as ManParser>::`
- [x] `fn is_my_type`—[claimed by scooter-dangle](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473981803)—#24
- [x] `fn parse_man_page`—claimed by @charliethomson —#81

- - -

`TypeDarwin::`
- [x] `fn trim_groff` —[claimed by AlanSwenson](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-474007263)—#22
- [x] `fn count_argument_dashes` —[claimed by AlanSwenson](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-474658637)
- [x] `fn groff_replace_escapes`—[claimed by AlanSwenson](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473732337) #13
- [x] `fn is_option`—#12

- - -

`<TypeDeroff as ManParser>::`
- [x] `fn is_my_type`—[claimed by scooter-dangle](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473981803)—#24
- [x] `fn parse_man_page`—claimed by @scooter-dangle—#91

- - -

`TypeDeroff::`
- [x] `fn is_option`—[claimed by AlanSwenson](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-473708890) #12
- [x] `fn could_be_description`—#11

- - -

- [x] `fn file_is_overwritable`—[claimed by AlanSwenson](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-482389297)
- [x] `fn cleanup_autogenerated_completions_in_directory`—claimed by @pickfire -- #97
- [x] `fn cleanup_autogenerated_file`-[claimed by AlanSwenson](https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-492875303)
- [x] `fn parse_manpage_at_path` —~~claimed by @necaris~~ —stolen by @pickfire
- [x] `fn parse_and_output_man_pages`—claimed by @charliethomson -- #96
- [x] `fn get_paths_from_man_locations`—claimed by @pickfire

### `deroff.rs`
`Deroffer::`
- [x] `fn g_specs_specletter` -- #14
- [x] `fn g_specs`--  #14
- [x] `const g_re_word` -- #37 
- [x] `const g_re_number` -- #37 
- [x] `const g_re_esc_char` -- #37 
- [x] `const g_re_not_backslash_or_whitespace` -- #37 
- [x] `const g_re_newline_collapse` -- #37 
- [x] `const g_re_font` -- #37 
- [x] `fn g_macro_dict` -- #40
- [x] `fn __init__` -- #59
- [x] `fn flush_output` --https://github.com/rust-dc/fish-manpage-completions/pull/53
- [x] `fn get_output` --https://github.com/rust-dc/fish-manpage-completions/pull/53
- [x] `fn putchar`
- [x] `fn condputs_tr` -- claimed by ~~@kbknapp~~ @charliethomson—#64
- [x] `fn condputs` -- claimed by ~~@kbknapp~~ @charliethomson—#64
- [x] `fn str_at` -- https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-491112572
- [x] `fn skip_char` -- https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-491112572
- [x] `fn skip_leading_whitespace` -- https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-491112572
- [x] `fn is_white` -- https://github.com/rust-dc/fish-manpage-completions/issues/2#issuecomment-491112572
- [x] ~~`fn str_eq`—claimed by @benjaminrsherman (#80)~~ (unused)
- [x] `fn prch` -- claimed by purew
- [x] `fn font`—claimed by @charliethomson
- [x] `fn font2` -- claimed by purew
- [x] `fn comment`—claimed by @pickfire (#61)
- [x] `fn numreq`—claimed by @charliethomson
- [x] `fn var`—claimed by @charliethomson
- [x] `fn size`—claimed by @charliethomson
- [x] `fn spec` --claimed by purew
- [x] `fn esc`—claimed by @charliethomson
- [x] `fn word`—claimed by @charliethomson
- [x] `fn text`—claimed by @charliethomson
- [x] `fn letter`—claimed by @pmatseykanets #54 
- [x] `fn digit`—claimed by @pmatseykanets #55 
- [x] `fn number`—claimed by @rschmertz #79 
- [x] `fn esc_char_backslash`—claimed by @sstanfield
- [x] `fn esc_char`—claimed by @sstanfield—#58
- [x] `fn quoted_arg`—claimed by @sstanfield—#58
- [x] `fn text_arg` -- #60 
- [x] `fn text_arg2` (unused: can 'implement' by removing the commented-out Python source)
- [x] `fn macro_sh` -- claimed by @kbknapp 
- [x] `fn macro_ss_ip` -- claimed by @kbknapp 
- [x] `fn macro_i_ir` -- claimed by @kbknapp 
- [x] `fn macro_nm`-- ~~claimed by @kbknapp~~ —stolen by @charliethomson 
- [x] `fn macro_close_bracket`-- claimed by @kbknapp 
- [x] `fn macro_ps` -- claimed by @kbknapp 
- [x] `fn macro_pe`—claimed by @charliethomson
- [x] `fn macro_ts`—claimed by @charliethomson
- [x] `fn macro_t_and`—claimed by @charliethomson
- [x] `fn macro_te`—claimed by @charliethomson
- [x] `fn macro_eq`—claimed by @charliethomson
- [x] `fn macro_en`—claimed by @charliethomson
- [x] `fn macro_r1`—claimed by @charliethomson
- [x] `fn macro_r2`—claimed by @charliethomson
- [x] `fn macro_de`—claimed by @charliethomson
- [x] `fn macro_bl_vl`—claimed by @charliethomson
- [x] `fn macro_bv`—claimed by @charliethomson
- [x] `fn macro_le`—claimed by @charliethomson
- [x] `fn macro_lp_pp`—claimed by @charliethomson
- [x] `fn macro_ds`—claimed by @charliethomson
- [x] `fn macro_so_nx`  -- claimed by @kbknapp 
- [x] `fn macro_tr` --claimed by ~~@PureW~~ @charliethomson
- [x] `fn macro_sp`—claimed by @charliethomson
- [x] `fn macro_other`—claimed by @charliethomson
- [x] `fn request_or_macro`—claimed by @charliethomson
- [x] `fn request_or_macro2`—claimed by @charliethomson
- [x] `fn do_tbl`—claimed by @charliethomson
- [x] `fn do_line` -- claimed by @kbknapp 
- [x] `fn deroff`—claimed by @charliethomson

- - -

- [x] `fn deroff_files`—claimed by @justinaustin

**Comment by necaris** [comment]
`deroff.py` -> `g_spec_specletter` and `g_spec` and `g_macro_dict`

**Comment by PureW** [comment]
`main.rs -> fish_escape_single_quotes` and `lossy_unicode`

**Comment by AlanSwenson** [comment]
main.rs -> could_be_description

**Comment by AlanSwenson** [comment]
`main.rs -> TypeDeroff::is_option`

**Comment by AlanSwenson** [comment]
`main.rs -> TypeDarwin::groff_replace_escapes`

**Comment by scooter-dangle** [comment]
> `deroff.py` -> `g_spec_specletter` and `g_spec` and `g_macro_dict`

Hmm...wasn't `g_specs_specletter` already done in master?

**Comment by necaris** [comment]
`deroff.rs` -> `const g_re_word`, const g_re_number, const g_re_esc_char, const g_re_not_backslash_or_whitespace, const g_re_newline_collapse, const g_re_font, fn __init__

**Comment by necaris** [comment]
@scooter-dangle I made a couple of changes to `g_specs_specletter` to return strings instead of byte vectors, based on what `deroffer.py` seemed to do, and had to make a matching change to the string literal format.

**Comment by scooter-dangle** [comment]
* `<{Type1, Type2, Type3, Type4, TypeDarwin, TypeDeroffManParser} as ManParser>::is_my_type`

**Comment by AlanSwenson** [comment]
`main.rs -> TypeDarwin::trim_groff`

**Comment by AlanSwenson** [comment]
`main.rs -> Type Darwin::count_argument_dashes`

**Comment by scooter-dangle** [comment]
`main.rs` &rarr; `built_command`

**Comment by AlanSwenson** [comment]
`main.rs` -> `file_is_overwritable`

**Comment by justinaustin** [comment]
`main.rs` -> `lossy_unicode`

**Comment by PureW** [comment]
deroff.rs -> skip_char

**Comment by AlanSwenson** [comment]
`main.rs` -> `cleanup_autogenerated_file`

**Comment by AlanSwenson** [comment]
`main.rd` -> `cleanup_autogenerated_completions_in_directory`

**Comment by necaris** [comment]
`deroff.rs` -> `macro_sh`

**Comment by justinaustin** [comment]
`deroff.rs` -> `deroff_files`

**Comment by rschmertz** [comment]
deroff.rs -> putchar

**Comment by pmatseykanets** [comment]
deroff.rs -> letter
deroff.rs -> digit

**Comment by scooter-dangle** [comment]
`main.rs` &rarr; `<TypeDeroff as ManParser>::parse_man_page`

**Comment by pickfire** [comment]
`main::get_paths_from_man_locations`

**Comment by necaris** [comment]
I would like to try `deroff::text_arg` !

**Comment by pickfire** [comment]
`comment` https://github.com/rust-dc/fish-manpage-completions/pull/61

**Comment by charliethomson** [comment]
`macro_pe` - `macro_en` B)

**Comment by charliethomson** [comment]
I'm gonna try and bang out the rest of deroff.rs, I'm officially claiming `request_or_macro` (and by extension `request_or_macro2`, which is worse and never gets used in the source), `font`, `numreq`, `var`, `size`, `esc`, `word`, `text`, and `esc_char_backlash`. I think after those and everyone else doing their part, we could definitely finish the rest of the file in no time.

**Comment by pickfire** [comment]
@scooter-dangle I believed `lossy_unicode` is already done?

**Comment by pickfire** [comment]
`main::Type1::fallback`
`main::Type1::fallback2`

**Comment by sstanfield** [comment]
Deroffer::esc_char_backslash

**Comment by necaris** [comment]
`main.rs` -> `parse_manpage_at_path`

**Comment by pickfire** [comment]
`main::Type1ManParser::parse_man_page`

**Comment by AlanSwenson** [comment]
unclaimed `fn cleanup_autogenerated_completions_in_directory`

**Comment by charliethomson** [comment]
Deroff.rs: do_tbl, deroff

**Comment by benjaminrsherman** [comment]
Claiming `str_eq`

**Comment by pickfire** [comment]
@benjaminrsherman `str_eq` does not seemed to be used anywhere.

**Comment by pickfire** [comment]
`main::Type2ManParser::parse_man_page`

**Comment by pickfire** [comment]
`main::Type4ManParser::parse_man_page`

**Comment by pickfire** [comment]
@dlrobertson Can I take `main::Type3ManParser::parse_man_page`? I did (not reviewed) the rest except `Darwin` which I am less willing to do.

**Comment by charliethomson** [comment]
im gonna do `main.rs:parse_and_output_man_pages`

**Comment by charliethomson** [comment]
`main::TypeDarwin::parse_man_page` -> #87

**Comment by pickfire** [comment]
We are at the edge of having a python parity with all the functions in place. Bumping those issues in parking lot to release their issues if needed (or anyone would like to steal these issues).

- `parse_manpage_at_path` @necaris 
- `parse_and_output_man_pages` @charliethomson 
- `macro_nm` @kbknapp
- `request_or_macro` @charliethomson
- `request_or_macro2` @charliethomson
- `do_tbl` @charliethomson
- `deroff` @charliethomson

Issues without an owner, I may take them if nobody wants.

- `cleanup_autogenerated_completions_in_directory`

**Comment by necaris** [comment]
@pickfire released my claim on `parse_manpage_at_path`, FWIW

**Comment by charliethomson** [comment]
I'm stealing the rest of deroff.rs, thanks :smile:

**Comment by pickfire** [comment]
I will be stealing parse `parse_manpage_at_path`.

**Comment by pickfire** [comment]
Looks like we are missing one most important function of all. `fn main()` @scooter-dangle ^^

**Comment by scooter-dangle** [comment]
> Looks like we are missing one most important function of all. `fn main()` the final boss we fight @scooter-dangle ^^

Haha. Yeap. Will add that sly devil.

**Comment by pickfire** [comment]
I steal `cleanup_autogenerated_completions_in_directory`

**Comment by pickfire** [comment]
Last boss remaining, I wish we could fight it together. :D @scooter-dangle What do you think?

**Comment by scooter-dangle** [comment]
> Last boss remaining, I wish we could fight it together. :D @scooter-dangle What do you think?

:dragon_face: 

Def. Might want to schedule a hack session for this week via Zulip?

**Comment by pickfire** [comment]
Thanks everyone for participating in this. Although it was long, we have ported it successfully.

Note that there may still be some minor differences since the porting was done long ago.
